spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/postgres
    username: postgres
    password: 1q2w3e4r
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MetadataHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true

logging:
  level:
    root: INFO
    com.example.metadata: DEBUG
    com.zaxxer.hikari: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.stat: WARN
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN

server:
  port: 8083

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:8000/postgres
    username: postgres
    password: 1q2w3e4r 