server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1q2w3e4r
    hikari:
      pool-name: MetadataHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 120000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.account.metadata: DEBUG
