services:
  postgres:
    image: postgres:15
    container_name: coz-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "8000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - coz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  apigw:
    build:
      context: .
      dockerfile: apigw/Dockerfile
    container_name: coz-apigw
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1q2w3e4r
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - coz-network
    restart: always

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: coz-auth
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1q2w3e4r
      - JWT_SECRET=your-256-bit-secret
      - JWT_EXPIRATION=3600
      - PROFILE_SERVICE_URL=http://profile:8084
    depends_on:
      postgres:
        condition: service_healthy
      profile:
        condition: service_started
    networks:
      - coz-network
    restart: always

  metadata:
    build:
      context: .
      dockerfile: metadata/Dockerfile
    container_name: coz-metadata
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1q2w3e4r
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - coz-network
    restart: always

  profile:
    build:
      context: .
      dockerfile: profile/Dockerfile
    container_name: coz-profile
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1q2w3e4r
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - coz-network
    restart: always

volumes:
  postgres-data:
    driver: local

networks:
  coz-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 