server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:8000/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1q2w3e4r
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    com.example.profile: DEBUG 