version: '3.8'
services:
  profile-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/profiledb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1q2w3e4r
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: profiledb
    environment:
      POSTGRES_DB: profiledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "5432:5432"
    restart: always 